services:
  redis:
    image: redis/redis-stack-server:latest
    # ports: 
    #   - 6379:6379

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka
    # ports:
    #   - "19092:19092"
    #   - "19093:19093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      # Изменено: теперь только один узел выполняет роль и брокера, и контроллера
      KAFKA_PROCESS_ROLES: 'broker,controller'
      # Изменено: только один voter (сам себя)
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:19093'
      KAFKA_LISTENERS: 'PLAINTEXT_INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:19093,PLAINTEXT_EXTERNAL://0.0.0.0:19092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_EXTERNAL://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT_INTERNAL'
      CLUSTER_ID: 'EmptNWtoR4GGWx-BH6nGLQ'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: password
    depends_on:
      - kafka

  clickhouse:
    image: clickhouse/clickhouse-server:24.1
    # ports:
    #   - "8123:8123"
    #   - "9000:9000"
    volumes:
      - clickhouse:/var/lib/clickhouse
      - /opt/platform/clickhouse/initprod:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: password
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    # docker run -it --rm --network platform_default clickhouse/clickhouse-client --host clickhouse

  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    environment:
      - CLICKHOUSE_URL=http://clickhouse:8123
    ports:
      - "3488:3488"


volumes:
  clickhouse:
