# https://taskfile.dev

version: '3'

vars:
  PG_CONNECT: user=admin password=123 dbname=admin_dev host=localhost port=6432 sslmode=disable

tasks:  
  gitpush:
    cmds:
      - git push gitflic master
      - git push sourcecraft master
      - git push github master
      - git push gitverse master

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  qor-install:
    cmds:
      - go install github.com/qor5/admin/v3/cmd/qor5@latest

  docker-up:
    cmds:
      - docker-compose up -d

  docker-down:
    cmds:
      - docker-compose down

  migration-status:
    cmds:
      - goose -dir ./migrations/postgres postgres "{{.PG_CONNECT}}" status

  migration-create:
    cmds:
      - goose -dir ./migrations/postgres postgres  "{{.PG_CONNECT}}" create {{.MIGRATION_NAME}} sql

  migration-up:
    cmds:
      - goose -dir ./migrations/postgres postgres  "{{.PG_CONNECT}}" up

  migration-down:
    cmds:
      - goose -dir ./migrations/postgres postgres  "{{.PG_CONNECT}}" down
