# https://taskfile.dev

version: '3'

vars:
  SERVICE_GROUP: adscoffee
  PG_CONNECT: user=admin password=123 dbname=admin_dev host=localhost port=6432 sslmode=disable

tasks:  
  gitpush:
    cmds:
      - git push gitflic master
      - git push sourcecraft master
      - git push github master
      - git push gitverse master

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run ./...

  docker-up:
    cmds:
      - docker-compose -f dev-compose.yaml up -d

  docker-down:
    cmds:
      - docker-compose -f dev-compose.yaml down
  
  migrate:
    cmds:
      - go run admin/cmd/admin/main.go -c ./admin/configs/config.yaml m

  docker-build-server:
    cmds:
      - docker build -t registry.gitflic.ru/project/kovardin/{{ .SERVICE_GROUP }}/platfom-server:latest -f Dockerfile.server .

  docker-publish-server:
    cmds:
      - docker push registry.gitflic.ru/project/kovardin/{{ .SERVICE_GROUP }}/platfom-server:latest

  docker-run-server:
    cmds:
     - docker run -p 8091:8081 -d registry.gitflic.ru/project/kovardin/{{ .SERVICE_GROUP }}/platfom-server:latest serve -c=configs/dev.yaml


  docker-build-admin:
    cmds:
      - docker build -t registry.gitflic.ru/project/kovardin/{{ .SERVICE_GROUP }}/platfom-admin:latest -f Dockerfile.server .

  docker-publish-admin:
    cmds:
      - docker push registry.gitflic.ru/project/kovardin/{{ .SERVICE_GROUP }}/platfom-admin:latest

  docker-run-admin:
    cmds:
     - docker run -p 8091:8081 -d registry.gitflic.ru/project/kovardin/{{ .SERVICE_GROUP }}/platfom-admin:latest serve -c=configs/dev.yaml

  deploy:
    cmds:
      - task: docker-build-server
      - task: docker-build-admin
      - task: docker-publish-server
      - task: docker-publish-admin
      # - task: docker-serve
