# https://taskfile.dev

version: '3'

vars:
  SERVER_VERSION: v0.2
  SERVER: miniservices
  NETWORK: production
  SERVICE_GROUP: adscoffee
  PG_CONNECT: user=admin password=123 dbname=admin_dev host=localhost port=6432 sslmode=disable

tasks:  
  gitpush:
    cmds:
      - git push gitflic master
      - git push sourcecraft master
      - git push github master
      - git push gitverse master

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run ./...

  docker-up:
    cmds:
      - docker-compose -f dev-compose.yaml up -d

  docker-down:
    cmds:
      - docker-compose -f dev-compose.yaml down
  
  migrate:
    cmds:
      - go run admin/cmd/admin/main.go -c ./admin/configs/config.yaml m

  docker-build-server:
    cmds:
      - docker build -t registry.gitflic.ru/project/kovardin/{{ .SERVICE_GROUP }}/platform-server:{{ .SERVER_VERSION }} -f Dockerfile.server .

  docker-publish-server:
    cmds:
      - docker push registry.gitflic.ru/project/kovardin/{{ .SERVICE_GROUP }}/platform-server:{{ .SERVER_VERSION }}

  docker-run-server:
    cmds:
     - docker run -p 8091:8081 -d -v /opt/platform/server/configs:/configs registry.gitflic.ru/project/kovardin/{{ .SERVICE_GROUP }}/platform-server:{{ .SERVER_VERSION }} serve -c=configs/dev.yaml

  
  docker-build-admin:
    cmds:
      - docker build -t registry.gitflic.ru/project/kovardin/{{ .SERVICE_GROUP }}/platform-admin:latest -f Dockerfile.admin .

  docker-publish-admin:
    cmds:
      - docker push registry.gitflic.ru/project/kovardin/{{ .SERVICE_GROUP }}/platform-admin:latest

  docker-run-admin:
    cmds:
     - docker run -p 8092:8082 -d -v /opt/platform/admin/configs:/configs registry.gitflic.ru/project/kovardin/{{ .SERVICE_GROUP }}/platform-admin:latest serve -c=configs/dev.yaml

  docker-serve-admin:
    cmds:
      - sup {{ .NETWORK }} docker-pull-admin
      - sup {{ .NETWORK }} docker-stop-admin
      - sup {{ .NETWORK }} docker-start-admin

  docker-serve-server:
    cmds:
      - sup -e SERVER_VERSION="{{ .SERVER_VERSION }}" {{ .NETWORK }} docker-pull-server
      - sup -e SERVER_VERSION="{{ .SERVER_VERSION }}" {{ .NETWORK }} docker-stop-server
      - sup -e SERVER_VERSION="{{ .SERVER_VERSION }}" {{ .NETWORK }} docker-start-server

  configs-server:
    cmds:
      - scp ./server/configs/prod.yaml {{ .SERVER }}:/opt/platform/server/configs/prod.yaml


  configs-admin:
    cmds:
      - scp ./admin/configs/prod.yaml {{ .SERVER }}:/opt/platform/admin/configs/prod.yaml

  deploy-server:
    cmds:
      - task: docker-build-server
      - task: docker-publish-server
      - task: docker-serve-server

  deploy-admin:
    cmds:
      - task: docker-build-admin
      - task: docker-publish-admin
      - task: docker-serve-admin

  deploy:
    cmds:
      - task: deploy-server
      - task: deploy-admin

  serve:
    cmds:
      - scp ./deploy/nginx/admin.ads.coffee {{ .SERVER }}:/etc/nginx/sites-available/
      - scp ./deploy/nginx/platform.ads.coffee {{ .SERVER }}:/etc/nginx/sites-available/
      - sup {{ .NETWORK }} nginx

  letsencrypt:
    cmds:
      - sup {{ .NETWORK }} letsencrypt