server:
  port: ":8080"

database:
  debug: false
  user: admin
  password: 123
  host: localhost
  port: 6432
  dbname: admin_dev

s3storage:
  bucket: "adscoffee"
  s3Endpoint: "http://localhost:9222"
  accessId: "root"
  accessKey: "rootpass123"
  region: "RU"
  s3ForcePathStyle: true

clickhouse:
  host: 127.0.0.1
  port: 9000
  user: user
  password: password
  database: analytics
  max_open_conns: 20
  max_idle_conns: 4
  max_conn_lifetime: "1m"